import { notFound } from "next/navigation";

export default async function CustomDomainDocsPage({
  params,
}: {
  params: { domain: string; slug?: string[] };
}) {
  const { domain, slug } = await params;

  // In a real app, you would fetch doc content from your database/Firebase
  // using the 'domain' to identify the project and 'slug' to identify the page.
  
  // MOCK DATA for demonstration:
  const isRegisteredDomain = domain === "docs.example.com" || domain.includes("localhost");
  
  if (!isRegisteredDomain) {
    // If domain isn't in our DB, show 404
    // return notFound();
  }

  return (
    <div className="min-h-screen bg-white text-slate-900 font-sans">
      {/* Docs Header */}
      <header className="sticky top-0 z-40 w-full backdrop-blur border-b border-slate-100 bg-white/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded bg-slate-900 flex items-center justify-center text-white font-bold text-xs">
              SQ
            </div>
            <span className="font-bold text-slate-900">{domain}</span>
          </div>
          <div className="flex items-center gap-6 text-sm font-medium text-slate-500">
            <a href="#" className="hover:text-slate-900">Guides</a>
            <a href="#" className="hover:text-slate-900">API Reference</a>
            <a href="#" className="hover:text-slate-900">Support</a>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex gap-12">
        {/* Sidebar */}
        <aside className="w-64 flex-shrink-0 hidden lg:block">
          <nav className="space-y-8 sticky top-28">
            <div>
              <h4 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4">Getting Started</h4>
              <ul className="space-y-3 text-sm text-slate-600">
                <li><a href="#" className="text-slate-900 font-bold">Introduction</a></li>
                <li><a href="#" className="hover:text-slate-900">Quickstart</a></li>
                <li><a href="#" className="hover:text-slate-900">Authentication</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4">Core Concepts</h4>
              <ul className="space-y-3 text-sm text-slate-600">
                <li><a href="#" className="hover:text-slate-900">The Graph</a></li>
                <li><a href="#" className="hover:text-slate-900">Agents & Tasks</a></li>
                <li><a href="#" className="hover:text-slate-900">State Persistence</a></li>
              </ul>
            </div>
          </nav>
        </aside>

        {/* Content */}
        <main className="flex-1 max-w-3xl">
          <div className="prose prose-slate prose-headings:font-bold prose-h1:text-4xl prose-h1:tracking-tight max-w-none">
            <p className="text-sm font-bold text-indigo-600 mb-2 uppercase tracking-wide">Documentation</p>
            <h1 className="mb-4">Introduction to {domain}</h1>
            <p className="text-xl text-slate-500 mb-10 leading-relaxed">
              This documentation was automatically generated by <span className="font-bold text-slate-900">ShipQuill</span>. 
              Your agents analyzed the source code of this project and produced this live reference.
            </p>

            <hr className="border-slate-100 my-12" />

            <h2 className="text-2xl mt-12 mb-6">Overview</h2>
            <p className="text-slate-600 leading-relaxed mb-6">
              Welcome to your new documentation site. This page is currently serving as a placeholder for the content associated with 
              <code className="bg-slate-50 px-1.5 py-0.5 rounded border border-slate-100 text-indigo-600">{slug?.join("/") || "root"}</code>.
            </p>

            <div className="bg-slate-50 border border-slate-100 rounded-2xl p-8 my-10">
              <h4 className="text-sm font-bold text-slate-900 mb-2 flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-indigo-500"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
                Next Steps
              </h4>
              <p className="text-sm text-slate-500 leading-relaxed">
                To start writing real content, push changes to your linked repository or update the Markdown files in your dashboard.
              </p>
            </div>

            <h2 className="text-2xl mt-12 mb-6">Deployment Status</h2>
            <div className="flex items-center gap-4 text-sm font-medium p-4 bg-green-50 border border-green-100 rounded-xl text-green-700">
              <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              This documentation is live and up-to-date with your latest commit.
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
